[package]
name = "lighthouse"
description = "Virtual reality basestation power management in Rust"
version = "1.5.0"
authors = ["Shayne Hartford <shaybox@shaybox.com>"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/ShayBox/Lighthouse"
license = "MIT"
keywords = ["bluetooth", "valve", "htc", "basestation", "lighthouse"]
categories = ["asynchronous", "command-line-utilities", "hardware-support"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "lighthouse"
required-features = ["cli"]

[features]
cli = ["clap", "clap-verbosity-flag", "tracing", "tracing-log", "tracing-subscriber"]
tracing = ["dep:tracing"]

[dependencies]
btleplug = { version = "0.12", features = ["serde"] }
clap = { version = "4", optional = true }
clap-verbosity-flag = { version = "3", optional = true }
thiserror = "2"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", optional = true }
tracing-log = { version = "0.2", optional = true }
tracing-subscriber = { version = "0.3", optional = true }
uuid = "1"

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
multiple_crate_versions = "allow"
