on:
  release:
    types: [ created ]

jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BIN_EXT: ${{ contains(matrix.target, 'windows') && '.exe' || '' }}
      LIB_PREFIX: ${{ contains(matrix.target, 'windows') && 'lighthouse' || 'liblighthouse' }}
      LIB_EXT: ${{ contains(matrix.target, 'windows') && '.dll' || (contains(matrix.target, 'darwin') && '.dylib' || '.so') }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux-aarch64
            target: aarch64-unknown-linux-gnu
            runner: ubuntu-26.04-arm

          - name: Linux-x86_64
            target: x86_64-unknown-linux-gnu
            runner: ubuntu-26.04

          - name: macOS-Apple-aarch64
            target: aarch64-apple-darwin
            runner: macos-26

          - name: macOS-Intel-x86_64
            target: x86_64-apple-darwin
            runner: macos-26-intel

          - name: Windows-aarch64
            target: aarch64-pc-windows-msvc
            runner: windows-11-arm

          - name: Windows-x86_64
            target: x86_64-pc-windows-msvc
            runner: windows-2025

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3

      - name: Update and Install Dependencies (Linux)
        if: ${{ contains(matrix.runner, 'ubuntu') }}
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y libdbus-1-dev

      - name: Update Rust Toolchain
        run: rustup update stable

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Build Release Binary
        run: cargo build --release --features cli --target ${{ matrix.target }}

      - name: Upload Release Assets
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/lighthouse$BIN_EXT "lighthouse-${{ matrix.target }}$BIN_EXT"
          cp target/${{ matrix.target }}/release/$LIB_PREFIX$LIB_EXT "$LIB_PREFIX-${{ matrix.target }}$LIB_EXT"
          gh release upload "${{ github.ref_name }}" "lighthouse-${{ matrix.target }}$BIN_EXT" "$LIB_PREFIX-${{ matrix.target }}$LIB_EXT" include/lighthouse.h --clobber

      - name: Upload Import Library (Windows)
        if: ${{ contains(matrix.target, 'windows') }}
        shell: bash
        run: |
          cp target/${{ matrix.target }}/release/$LIB_PREFIX.dll.lib "$LIB_PREFIX-${{ matrix.target }}.dll.lib"
          gh release upload "${{ github.ref_name }}" "$LIB_PREFIX-${{ matrix.target }}.dll.lib" --clobber
